# Generated by Django 4.1.4 on 2022-12-18 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=65535)),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('is_correct', models.BooleanField()),
            ],
            options={
                'ordering': ('-question', '-date_posted'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField()),
                ('premium', models.BooleanField()),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='QueueUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('displayed_name', models.CharField(max_length=12)),
                ('birthday', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.BooleanField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('slug', models.SlugField()),
                ('queue_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('displayed_name',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=65535)),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='forum.category')),
                ('community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community', to='forum.community')),
                ('queue_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_user_questions', to='forum.queueuser')),
            ],
            options={
                'ordering': ('-date_posted',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=65535)),
                ('suggested_edit', models.BooleanField()),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_comments', to='forum.answer')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_comments', to='forum.question')),
                ('queue_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_user_comments', to='forum.queueuser')),
            ],
            options={
                'ordering': ('question', '-date_posted'),
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forum.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='queue_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_user_answers', to='forum.queueuser'),
        ),
    ]
