# Generated by Django 4.1.4 on 2023-02-05 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='community',
        ),
        migrations.RemoveField(
            model_name='queueuser',
            name='subscription',
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='forum.category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='queue_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_user_questions', to='forum.queueuser'),
        ),
        migrations.DeleteModel(
            name='Community',
        ),
    ]
