# Generated by Django 4.1.4 on 2023-02-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_question_downvotes_alter_question_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(max_length=65535, null=True),
        ),
    ]
