# Generated by Django 4.1.4 on 2023-02-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_remove_question_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='<built-in function id>'),
        ),
    ]
