# Generated by Django 4.1.4 on 2023-02-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_question_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
    ]
